{{
    config(
        materialized='table',
        tags=['bronze']
    )
}}

select
    -- provider identity
    rndrng_npi,
    rndrng_prvdr_last_org_name,
    rndrng_prvdr_first_name,
    rndrng_prvdr_mi,
    rndrng_prvdr_crdntls,
    rndrng_prvdr_ent_cd,
    rndrng_prvdr_st1,
    rndrng_prvdr_st2,
    rndrng_prvdr_city,
    rndrng_prvdr_state_abrvtn,
    rndrng_prvdr_state_fips,
    rndrng_prvdr_zip5,
    rndrng_prvdr_ruca,
    rndrng_prvdr_ruca_desc,
    rndrng_prvdr_cntry,
    rndrng_prvdr_type,
    rndrng_prvdr_mdcr_prtcptg_ind,
    -- overall utilization totals
    tot_hcpcs_cds,
    tot_benes,
    tot_srvcs,
    tot_sbmtd_chrg,
    tot_mdcr_alowd_amt,
    tot_mdcr_pymt_amt,
    tot_mdcr_stdzd_amt,
    -- drug service totals
    drug_sprsn_ind,
    drug_tot_hcpcs_cds,
    drug_tot_benes,
    drug_tot_srvcs,
    drug_sbmtd_chrg,
    drug_mdcr_alowd_amt,
    drug_mdcr_pymt_amt,
    drug_mdcr_stdzd_amt,
    -- medical service totals
    med_sprsn_ind,
    med_tot_hcpcs_cds,
    med_tot_benes,
    med_tot_srvcs,
    med_sbmtd_chrg,
    med_mdcr_alowd_amt,
    med_mdcr_pymt_amt,
    med_mdcr_stdzd_amt,
    -- beneficiary demographics
    bene_avg_age,
    bene_age_lt_65_cnt,
    bene_age_65_74_cnt,
    bene_age_75_84_cnt,
    bene_age_gt_84_cnt,
    bene_feml_cnt,
    bene_male_cnt,
    bene_race_wht_cnt,
    bene_race_black_cnt,
    bene_race_api_cnt,
    bene_race_hspnc_cnt,
    bene_race_natind_cnt,
    bene_race_othr_cnt,
    bene_dual_cnt,
    bene_ndual_cnt,
    -- behavioral health chronic condition prevalence
    bene_cc_bh_adhd_othcd_v1_pct,
    bene_cc_bh_alcohol_drug_v1_pct,
    bene_cc_bh_tobacco_v1_pct,
    bene_cc_bh_alz_nonalzdem_v2_pct,
    bene_cc_bh_anxiety_v1_pct,
    bene_cc_bh_bipolar_v1_pct,
    bene_cc_bh_mood_v2_pct,
    bene_cc_bh_depress_v1_pct,
    bene_cc_bh_pd_v1_pct,
    bene_cc_bh_ptsd_v1_pct,
    bene_cc_bh_schizo_othpsy_v1_pct,
    -- physical health chronic condition prevalence
    bene_cc_ph_asthma_v2_pct,
    bene_cc_ph_afib_v2_pct,
    bene_cc_ph_cancer6_v2_pct,
    bene_cc_ph_ckd_v2_pct,
    bene_cc_ph_copd_v2_pct,
    bene_cc_ph_diabetes_v2_pct,
    bene_cc_ph_hf_nonihd_v2_pct,
    bene_cc_ph_hyperlipidemia_v2_pct,
    bene_cc_ph_hypertension_v2_pct,
    bene_cc_ph_ischemicheart_v2_pct,
    bene_cc_ph_osteoporosis_v2_pct,
    bene_cc_ph_parkinson_v2_pct,
    bene_cc_ph_arthritis_v2_pct,
    bene_cc_ph_stroke_tia_v2_pct,
    bene_avg_risk_scre,
    current_timestamp() as _loaded_at
from {{ source('bronze', 'provider_claims_raw') }}
